name: brainyhome_api
description: A Brainy Home API connector plugin
version: 0.10.2
author: Oqtavios
homepage: https://github.com/Oqtavios/brainyhome_api

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
