name: brainyhome_api
description: A Brainy Home API connector package
version: 0.12.12
homepage: https://github.com/Oqtavios/brainyhome_api

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.0.0
