name: brainyhome_api
description: A Brainy Home API connector package
version: 0.12.9
homepage: https://github.com/Oqtavios/brainyhome_api

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0
