name: brainyhome_api
description: A Brainy Home API connector package
version: 0.11.5
author: Oqtavios
homepage: https://github.com/Oqtavios/brainyhome_api

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.13.0
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
